'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Associados

    Partial Public Class Detalhes

        '''<summary>
        '''lblNome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNome As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCPF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCPF As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDataNascimento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDataNascimento As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''GridViewEmpresas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewEmpresas As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnVoltar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnVoltar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
