'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Empresas

    Partial Public Class Cadastro

        '''<summary>
        '''txtNome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCNPJ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCNPJ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lstAssociados control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstAssociados As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''lblErro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnIncluir control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnIncluir As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnVoltar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnVoltar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
