'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Empresas

    Partial Public Class Lista

        '''<summary>
        '''txtFiltroNome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFiltroNome As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFiltroCNPJ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFiltroCNPJ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnPesquisar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPesquisar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNovo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNovo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''GridViewEmpresas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewEmpresas As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
